The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) Stages/2025

The following have been reloaded with a version change:
  1) sympy/1.13.3 => sympy/1.13.1

WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[W721 14:11:58.237700402 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[W721 14:11:58.255316930 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:08.553219083 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:08.568374744 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:08.568373674 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:08.553307843 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:08.568614555 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:08.553773597 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:09.572265149 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[W721 14:12:09.562777463 socket.cpp:752] [c10d] The client socket cannot be initialized to connect to [jrc0298i.jureca]:7010 (errno: 97 - Address family not supported by protocol).
[rank2]: Traceback (most recent call last):
[rank2]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank2]:     main(args)
[rank2]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank2]:     model.fit_distributed(
[rank2]:     ^^^^^^^^^^^^^^^^^^^^^
[rank2]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank2]:     raise AttributeError(
[rank2]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank0]:     main(args)
[rank0]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank0]:     model.fit_distributed(
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank0]:     raise AttributeError(
[rank0]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank1]: Traceback (most recent call last):
[rank1]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank1]:     main(args)
[rank1]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank1]:     model.fit_distributed(
[rank1]:     ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank1]:     raise AttributeError(
[rank1]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank3]: Traceback (most recent call last):
[rank3]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank3]:     main(args)
[rank3]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank3]:     model.fit_distributed(
[rank3]:     ^^^^^^^^^^^^^^^^^^^^^
[rank3]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank3]:     raise AttributeError(
[rank3]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank5]: Traceback (most recent call last):
[rank5]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank5]:     main(args)
[rank5]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank5]:     model.fit_distributed(
[rank5]:     ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank5]:     raise AttributeError(
[rank5]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank7]: Traceback (most recent call last):
[rank7]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank7]:     main(args)
[rank7]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank7]:     model.fit_distributed(
[rank7]:     ^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank7]:     raise AttributeError(
[rank7]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank6]: Traceback (most recent call last):
[rank6]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank6]:     main(args)
[rank6]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank6]:     model.fit_distributed(
[rank6]:     ^^^^^^^^^^^^^^^^^^^^^
[rank6]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank6]:     raise AttributeError(
[rank6]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank4]: Traceback (most recent call last):
[rank4]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 153, in <module>
[rank4]:     main(args)
[rank4]:   File "/p/project1/training2529/marxen1/amm-risk-lab/python/ml/PLV/scripts/run_ddp_training.py", line 109, in main
[rank4]:     model.fit_distributed(
[rank4]:     ^^^^^^^^^^^^^^^^^^^^^
[rank4]:   File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
[rank4]:     raise AttributeError(
[rank4]: AttributeError: 'DistributedDataParallel' object has no attribute 'fit_distributed'
[rank0]:[W721 14:12:52.922595697 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[rank4]:[W721 14:12:52.916786602 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W0721 14:12:53.703000 2033491 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2033529 closing signal SIGTERM
W0721 14:12:53.710000 2033491 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2033531 closing signal SIGTERM
W0721 14:12:53.717000 2033491 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2033532 closing signal SIGTERM
W0721 14:12:53.720000 2501755 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2501794 closing signal SIGTERM
W0721 14:12:53.728000 2501755 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2501795 closing signal SIGTERM
W0721 14:12:53.735000 2501755 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2501797 closing signal SIGTERM
E0721 14:12:54.151000 2033491 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 1 (pid: 2033530) of binary: /p/home/jusers/marxen1/jureca/course/sc_venv_template/venv/bin/python3
E0721 14:12:54.170000 2501755 /p/software/fs/jurecadc/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 2501796) of binary: /p/home/jusers/marxen1/jureca/course/sc_venv_template/venv/bin/python3
Traceback (most recent call last):
  File "/p/home/jusers/marxen1/jureca/course/sc_venv_template/venv/bin/torchrun_jsc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/p/project1/training2529/marxen1/amm-risk-lab/envs/jureca0/venv/lib/python3.12/site-packages/torchrun_jsc/__init__.py", line 44, in main
    run_main()
  File "/p/project1/training2529/marxen1/amm-risk-lab/envs/jureca0/venv/lib/python3.12/site-packages/torchrun_jsc/run.py", line 91, in main
    runpy.run_module('torch.distributed.run', run_name='__main__')
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
python/ml/PLV/scripts/run_ddp_training.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-21_14:12:53
  host      : jrc0298.jureca
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2033530)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/p/home/jusers/marxen1/jureca/course/sc_venv_template/venv/bin/torchrun_jsc", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/p/project1/training2529/marxen1/amm-risk-lab/envs/jureca0/venv/lib/python3.12/site-packages/torchrun_jsc/__init__.py", line 44, in main
    run_main()
  File "/p/project1/training2529/marxen1/amm-risk-lab/envs/jureca0/venv/lib/python3.12/site-packages/torchrun_jsc/run.py", line 91, in main
    runpy.run_module('torch.distributed.run', run_name='__main__')
  File "<frozen runpy>", line 229, in run_module
  File "<frozen runpy>", line 88, in _run_code
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/run.py", line 923, in <module>
    main()
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/p/software/default/stages/2025/software/PyTorch/2.5.1-gcccoreflexiblas-13.3.0-3.4.4/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
python/ml/PLV/scripts/run_ddp_training.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-21_14:12:53
  host      : jrc0310.jureca
  rank      : 6 (local_rank: 2)
  exitcode  : 1 (pid: 2501796)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: jrc0310: task 1: Exited with exit code 1
srun: error: jrc0298: task 0: Exited with exit code 1
